SCR_MissionHeader {
 World "{B7794795D99959E4}worlds/anteante101/Castle Crushers/CastleCrushers.ent"
 m_sName "TVT (20-40) Castle Crushers"
 m_sAuthor "anteante101"
 m_sDescription "IRA defend themselves from the British at the Castle of Lord Kevin"
 m_iPlayerCount 40
}