SCR_MissionHeader {
 World "{17BA46B2D7A10B37}worlds/anteante101/Its all uphill from here/Its all uphill from here.ent"
 m_sName "COTVT (9-18) Its all uphill from here"
 m_sAuthor "anteante101"
 m_sDescription "A insurgent cell defends themselves and their loyal force from the rival warlord and his mercenaries."
 m_iPlayerCount 19
}