SCR_MissionHeader {
 World "{CD72FCF714A5065F}worlds/anteante101/RoleReversal/RoleReversal.ent"
 m_sName "TVT (5-19) Role Reversal"
 m_sAuthor "anteante101"
 m_sDescription "A insurgent squad fights off a US Army squad to extract a HVT"
 m_iPlayerCount 19
}