SCR_MissionHeader {
 World "{62E19E08D663F36D}worlds/anteante101/South wind is blowing/South wind is blowing.ent"
 m_sName "TVT (20-41) South wind is blowing"
 m_sAuthor "anteante101"
 m_sDescription "A brand new FIA platoon consisting of mostly former civilians is assaulting a US military base"
 m_iPlayerCount 41
 m_GC_Metadata GC_MissionMetadata "{6A02EA3CE6E67803}" {
  m_FriendlyForce GC_ForceDefinition "{6A02EA3CED643662}" {
   m_sFactionKey "FIA"
   m_eType MOTORIZED
  }
  m_OpposingForce GC_ForceDefinition "{6A02EA3CF9882EDB}" {
   m_sFactionKey "US"
  }
  m_eEra ERA_1980s
 }
}