SCR_MissionHeader {
 World "{A9E5675A967E8F1A}worlds/Burn0ut7/Farm/Farm.ent"
 m_sName "TVT (55-73) Farm"
 m_sAuthor "Burn0ut7"
 m_sDescription "CDF assaults open fields and fortified russian positions"
 m_iPlayerCount 73
}