SCR_MissionHeader {
 World "{780B1971855B9884}worlds/FloridaMan/worlds/PreciousMinerals/PreciousMinerals.ent"
 m_sName "TVT (37-86) Precious Minerals"
 m_sAuthor "FloridaMan"
 m_sDescription "CAF re-secure a precious minerals mine captured by separatist forces."
 m_sGameMode "TVT"
 m_iPlayerCount 86
 m_iMapMarkerLimitPerPlayer 69
}