SCR_MissionHeader {
 World "{9AF99979E3CE957D}worlds/Gabe/IronResolve/IronResolve.ent"
 m_sName "TVT (51-68) Iron Resolve"
 m_sAuthor "Gabe"
 m_sDescription "US Army platoon assaults Iraqi city held by insurgents with support of HMMWVs and Strykers."
 m_iPlayerCount 68
}