SCR_MissionHeader {
 World "{6F1C0285DD0377AD}worlds/IronFunnelEvent/MSN3/SovietLevies.ent"
 m_sName "TVT (80-108) Soviet Levies"
 m_sAuthor "Blue"
 m_sDescription "Iron Funnel Event/Campaign, Mission 3."
 m_iPlayerCount 108
 m_GC_Metadata GC_MissionMetadata "{69F15DAF2F2FC3F8}" {
  m_FriendlyForce GC_ForceDefinition "{69F15DAF371D48CF}" {
   m_sFactionKey "US"
   m_eType LIGHT
  }
  m_OpposingForce GC_ForceDefinition "{69F15DAF3768DF0A}" {
   m_sFactionKey "USSR"
   m_eType MECHANIZED
  }
  m_eEra ERA_1980s
  m_eSpecialAssets {
   MORTARS
  }
 }
}