SCR_MissionHeader {
 World "{871F3A8DE6BCEF45}worlds/Gabe/BlocParty/BlocParty.ent"
 m_sName "TVT (68-99) Bloc Party"
 m_sAuthor "Gabe"
 m_sDescription "In Syria, a company (-) of Russian Army infantry, with the support of TIGRs, push anti-Assad Rebels deeper into the city."
 m_iPlayerCount 99
}