SCR_MissionHeader {
 World "{062FCE90122B59D9}worlds/Til/ALittleWhileLonger/ALittleWhileLonger.ent"
 m_sName "TVT (33-45) A Little While Longer"
 m_sAuthor "Til"
 m_sDescription "CDF attempt to delay Russians in order to cover the withdrawal of friendly forces"
 m_sGameMode "#AR-ServerBrowser_ServerScenario"
 m_iPlayerCount 45
 m_GC_Metadata GC_MissionMetadata "{69DF2BF03F8F617D}" {
  m_FriendlyForce GC_ForceDefinition "{69DF2BF03D797082}" {
   m_sFactionKey "RHS_AFRF"
   m_eType LIGHT
  }
  m_OpposingForce GC_ForceDefinition "{69DF2BF03DF8459F}" {
   m_sFactionKey "GC_CDF"
   m_eType LIGHT
  }
  m_eEra ERA_2020s
  m_eSpecialAssets {
   DRONES
  }
 }
}