SCR_MissionHeader {
 World "{062FCE90122B59D9}worlds/Til/ALittleWhileLonger/ALittleWhileLonger.ent"
 m_sName "TVT (33-45) A Little While Longer"
 m_sAuthor "Til"
 m_sDescription "CDF attempt to delay Russians in order to cover the withdrawal of friendly forces"
 m_sGameMode "#AR-ServerBrowser_ServerScenario"
 m_iPlayerCount 45
}