SCR_MissionHeader {
 World "{B53C28C3BCE039A8}worlds/Til/CompanyTeamCounterAttack/CompanyTeamCounterAttack.ent"
 m_sName "COTVT (40-57) Company Team Counter Attack"
 m_sAuthor "Til"
 m_sDescription "US 'tank and mechanized infantry company team' leads a counter attack against an East German motorized rifle battalion."
 m_sGameMode "#AR-ServerBrowser_ServerScenario"
 m_iPlayerCount 57
 m_GC_Metadata GC_MissionMetadata "{69DF2DD2A3BE83BE}" {
  m_FriendlyForce GC_ForceDefinition "{69DF2DD2A0D53CCA}" {
   m_sFactionKey "US"
   m_eType ARMORED
  }
  m_OpposingForce GC_ForceDefinition "{69DF2DD2A1D3E75E}" {
   m_sFactionKey "GC_NVA"
  }
  m_eEra ERA_1980s
  m_eSpecialAssets {
   TANKS
   ATK_HELIS
  }
 }
}