SCR_MissionHeader {
 World "{BB0A3AAF45B86C1F}worlds/Til/Countdown/Countdown.ent"
 m_sName "TVT (37-50) Countdown"
 m_sAuthor "Til"
 m_sDescription "1st Special Forces Operational Detachment–Delta attempts to prevent the detonation of a low-yield nuclear device."
 m_sGameMode "#AR-ServerBrowser_ServerScenario"
 m_iPlayerCount 53
 m_GC_Metadata GC_MissionMetadata "{69DF2DD2879336EE}" {
  m_FriendlyForce GC_ForceDefinition "{69DF2DD2852CFE90}" {
   m_sFactionKey "RHS_USAF"
   m_eType AIRMOBILE
  }
  m_OpposingForce GC_ForceDefinition "{69DF2DD289B86E45}" {
   m_sFactionKey "GC_SEPARATIST"
   m_eType LIGHT
  }
  m_eEra ERA_2010s
  m_eSpecialAssets {
   ATK_HELIS
   DRONES
   MORTARS
  }
 }
}