SCR_MissionHeader {
 World "{5D4D0310E22B589E}worlds/Til/DevilsDrive/DevilsDrive.ent"
 m_sName "TVT (85-105) Devil's Drive"
 m_sAuthor "Til"
 m_sDescription "A company team sent by the 2nd Armored Division performs a counterattack on a small East German covering force, seeking to allow a larger spearhead to move through and fight the Panzerregiment 22."
 m_iPlayerCount 105
 m_GC_Metadata GC_MissionMetadata "{69DF36771BC96F35}" {
  m_FriendlyForce GC_ForceDefinition "{69DF3677180EA500}" {
   m_sFactionKey "US"
   m_eType COMBINED
  }
  m_OpposingForce GC_ForceDefinition "{69DF367719C27AD0}" {
   m_sFactionKey "GC_NVA"
   m_eType COMBINED
  }
  m_eEra ERA_1980s
  m_eSpecialAssets {
   TANKS
  }
 }
}