SCR_MissionHeader {
 World "{2236987BB81F415A}worlds/Til/GreenScreen/GreenScreen.ent"
 m_sName "TVT (40-47) Green Screen"
 m_sAuthor "Til"
 m_sDescription "NVA reconnaissance company moves through a forest while a USMC LAR platoon is screening."
 m_sGameMode "#AR-ServerBrowser_ServerScenario"
 m_iPlayerCount 47
 m_GC_Metadata GC_MissionMetadata "{69DF3676CA780423}" {
  m_FriendlyForce GC_ForceDefinition "{69DF3676CAAB4C44}" {
   m_sFactionKey "GC_NVA"
   m_eType MECHANIZED
  }
  m_OpposingForce GC_ForceDefinition "{69DF3676CB2D2C3B}" {
   m_sFactionKey "US"
   m_eType MECHANIZED
  }
  m_eEra ERA_1980s
 }
}