SCR_MissionHeader {
 World "{E2FA07CE7BD8AEB6}worlds/Til/GullBayGuns/GullBayGuns.ent"
 m_sName "COOP (5-13) Gull Bay Guns"
 m_sAuthor "Til"
 m_sDescription "US Marines raid a Russian SPG Platoon"
 m_sGameMode "#AR-ServerBrowser_ServerScenario"
 m_iPlayerCount 13
 m_GC_Metadata GC_MissionMetadata "{69DF3676E76A135C}" {
  m_FriendlyForce GC_ForceDefinition "{69DF3676E79ED14E}" {
   m_sFactionKey "RHS_USAF"
   m_eType LIGHT
  }
  m_OpposingForce GC_ForceDefinition "{69DF3676E7B727ED}" {
   m_sFactionKey "RHS_AFRF"
   m_eType LIGHT
  }
  m_eEra ERA_2020s
 }
}