SCR_MissionHeader {
 World "{0537A0EFBC6F01ED}worlds/Til/HeatherBayHarbor/HeatherBayHarbor.ent"
 m_sName "COOP (10-17) Heather Bay Harbor"
 m_sAuthor "Til"
 m_sDescription "US forces seize a USSR-held harbor"
 m_sGameMode "#AR-ServerBrowser_ServerScenario"
 m_iPlayerCount 17
 m_GC_Metadata GC_MissionMetadata "{69DF367687D275F8}" {
  m_FriendlyForce GC_ForceDefinition "{69DF36769B787389}" {
   m_sFactionKey "US"
   m_eType LIGHT
  }
  m_OpposingForce GC_ForceDefinition "{69DF36769A97D136}" {
   m_sFactionKey "USSR"
   m_eType LIGHT
  }
  m_eEra ERA_1980s
 }
}