SCR_MissionHeader {
 World "{EE2DBE40557712DE}worlds/Til/JunctionJab/JunctionJab.ent"
 m_sName "COTVT (36-44) Junction Jab"
 m_sAuthor "Til"
 m_sDescription "An East German motor rifle platoon attempts to seize the settlement of Hnevice in order to cut off the approach towards Luzohrad, supporting an imminent assault on the town."\
 ""
 m_sGameMode "#AR-ServerBrowser_ServerScenario"
 m_iPlayerCount 44
}