SCR_MissionHeader {
 World "{EE2DBE40557712DE}worlds/Til/JunctionJab/JunctionJab.ent"
 m_sName "COTVT (36-44) Junction Jab"
 m_sAuthor "Til"
 m_sDescription "An East German motor rifle platoon attempts to seize the settlement of Hnevice in order to cut off the approach towards Luzohrad, supporting an imminent assault on the town."\
 ""
 m_sGameMode "#AR-ServerBrowser_ServerScenario"
 m_iPlayerCount 44
 m_GC_Metadata GC_MissionMetadata "{69DF36767E6D952B}" {
  m_FriendlyForce GC_ForceDefinition "{69DF3676A1BAEC2C}" {
   m_sFactionKey "GC_NVA"
   m_eType MECHANIZED
  }
  m_OpposingForce GC_ForceDefinition "{69DF3676A10454A9}" {
   m_sFactionKey "GC_CAF"
   m_eType LIGHT
  }
  m_eEra ERA_1980s
  m_eSpecialAssets {
   MORTARS
  }
  m_MissionGroup GC_MissionGroupDefinition "{69DF36767FE223C3}" {
   m_sGroupID "Junction Jab"
   m_fGroupSimilarity 0.9
  }
 }
}