SCR_MissionHeader {
 World "{8845D4E8D2187E5B}worlds/Til/KoskelankylaCrossing/KoskelankylaCrossing.ent"
 m_sName "TVT (39-49) Koskelankyla Crossing"
 m_sAuthor "Til"
 m_sDescription "NVA motorized rifle platoon attempts to secure a bridge defended by British light infantry"
 m_sGameMode "#AR-ServerBrowser_ServerScenario"
 m_iPlayerCount 49
 m_GC_Metadata GC_MissionMetadata "{69DF332D2333B8BB}" {
  m_FriendlyForce GC_ForceDefinition "{69DF332D2B75889E}" {
   m_sFactionKey "GC_NVA"
   m_eType MECHANIZED
  }
  m_OpposingForce GC_ForceDefinition "{69DF332D2ACDF4C0}" {
   m_sFactionKey "UK"
   m_eType MOTORIZED
  }
  m_eEra ERA_1980s
  m_eSpecialAssets {
   MORTARS
  }
 }
}