SCR_MissionHeader {
 World "{2A476B981689B7EE}worlds/Til/MetalsMight/MetalsMight.ent"
 m_sName "TVT (85-105) Metal's Might"
 m_sAuthor "Til"
 m_sDescription "Cut off by the prior air assault, two platoons of the 3rd ACR are forced into an engagement with the 9. PDs Panzerregiment 22, and have to attempt a delaying action."
 m_iPlayerCount 105
 m_GC_Metadata GC_MissionMetadata "{69DF332D0F7F7780}" {
  m_FriendlyForce GC_ForceDefinition "{69DF332D0C477B75}" {
   m_sFactionKey "GC_NVA"
   m_eType ARMORED
  }
  m_OpposingForce GC_ForceDefinition "{69DF332D0DC5DB52}" {
   m_sFactionKey "US"
   m_eType ARMORED
  }
  m_eEra ERA_1980s
  m_eSpecialAssets {
   TANKS
   MORTARS
  }
 }
}