SCR_MissionHeader {
 World "{43060BE6BD58243A}worlds/Til/OwlsPrey/OwlsPrey.ent"
 m_sName "COTVT (30-38) Owl's Prey"
 m_sAuthor "Til"
 m_sDescription "Chernarussian SF venture into the Green Sea, on the hunt for grass snakes."
 m_sGameMode "#AR-ServerBrowser_ServerScenario"
 m_iPlayerCount 38
 m_GC_Metadata GC_MissionMetadata "{69DF332CEC7F597D}" {
  m_FriendlyForce GC_ForceDefinition "{69DF332CED288493}" {
   m_sFactionKey "GC_CDF"
   m_eType AIRMOBILE
  }
  m_OpposingForce GC_ForceDefinition "{69DF332CEC978A1B}" {
   m_sFactionKey "RHS_AFRF"
   m_eType LIGHT
  }
  m_eEra ERA_2020s
  m_eSpecialAssets {
   ATK_HELIS
  }
 }
}