SCR_MissionHeader {
 World "{C54B35D900B45703}worlds/Til/RouteRowan/RouteRowan.ent"
 m_sName "TVT (29-37) Route Rowan"
 m_sAuthor "Til"
 m_sDescription "USMC LAR platoon conducts route security on Kolguyev"
 m_iPlayerCount 37
 m_GC_Metadata GC_MissionMetadata "{69DF332C726D2B1B}" {
  m_FriendlyForce GC_ForceDefinition "{69DF332C719B1D9F}" {
   m_sFactionKey "US"
   m_eType MECHANIZED
  }
  m_OpposingForce GC_ForceDefinition "{69DF332C71A702DD}" {
   m_sFactionKey "GC_SEPARATIST"
   m_eType LIGHT
  }
  m_eSpecialAssets {
   ATK_HELIS
  }
 }
}