SCR_MissionHeader {
 World "{E5BC48CC7021C3B9}worlds/Til/RoutePierre/RoutePierre.ent"
 m_sName "COOP (26-44) Route Pierre"
 m_sAuthor "Til"
 m_sDescription "Motorized USMC Rifle Platoon secures a route into the village of Vernon, which is defended by a Russian Motor Rifle company."
 m_sGameMode "#AR-ServerBrowser_ServerScenario"
 m_iPlayerCount 44
 m_GC_Metadata GC_MissionMetadata "{69DF332C1BF47A22}" {
  m_FriendlyForce GC_ForceDefinition "{69DF332C180E85D9}" {
   m_sFactionKey "RHS_USAF"
   m_eType MOTORIZED
  }
  m_OpposingForce GC_ForceDefinition "{69DF332C1855DDBD}" {
   m_sFactionKey "RHS_AFRF"
   m_eType MECHANIZED
  }
  m_eEra ERA_2020s
 }
}