SCR_MissionHeader {
 World "{ACD8062204E2C7FC}worlds/Til/RouteTremaux/RouteTremaux.ent"
 m_sName "COOP (18-26) Route Trémaux"
 m_sAuthor "Til"
 m_sDescription "USMC LAR platoon conducts route reconnaissance"
 m_iPlayerCount 26
 m_GC_Metadata GC_MissionMetadata "{6A3ED68204BEB063}" {
  m_FriendlyForce GC_ForceDefinition "{6A3ED68204BEB012}" {
   m_sFactionKey "US"
   m_eType MECHANIZED
  }
  m_OpposingForce GC_ForceDefinition "{6A3ED68204BEB011}" {
   m_sFactionKey "GC_SEPARATIST"
   m_eType LIGHT
  }
  m_eEra ERA_1990s
 }
}