SCR_MissionHeader {
 World "{5736E0A9D1D26445}worlds/Til/TheAdjacentWave/TheAdjacentWave.ent"
 m_sName "COTVT (18-23) The Adjacent Wave"
 m_sAuthor "Til"
 m_sDescription "Russian light motor rifle assault on CDF position"
 m_sGameMode "#AR-ServerBrowser_ServerScenario"
 m_iPlayerCount 23
 m_GC_Metadata GC_MissionMetadata "{69DF332CA9C63C2D}" {
  m_FriendlyForce GC_ForceDefinition "{69DF332CAE3A3AC5}" {
   m_sFactionKey "RHS_AFRF"
   m_eType MOTORIZED
  }
  m_OpposingForce GC_ForceDefinition "{69DF332CB12BB6C6}" {
   m_sFactionKey "GC_CDF"
   m_eType LIGHT
  }
  m_eEra ERA_2020s
 }
}