SCR_MissionHeader {
 World "{360FED920A0A73AC}worlds/Til/TrenchAssault/TrenchAssault.ent"
 m_sName "COTVT (12-18) Trench Assault"
 m_sAuthor "Til"
 m_sDescription "Chernarussian SF assault a Russian trench"
 m_sGameMode "#AR-ServerBrowser_ServerScenario"
 m_iPlayerCount 18
 m_GC_Metadata GC_MissionMetadata "{69DF332C3D679B97}" {
  m_FriendlyForce GC_ForceDefinition "{69DF332C0ED6E13B}" {
   m_sFactionKey "GC_CDF"
   m_eType LIGHT
  }
  m_OpposingForce GC_ForceDefinition "{69DF332C0E1DADDA}" {
   m_sFactionKey "RHS_AFRF"
   m_eType LIGHT
  }
  m_eEra ERA_2020s
 }
}