SCR_MissionHeader {
 World "{D3423DC8D54D19BC}worlds/Til/TyroneThrust/TyroneThrust.ent"
 m_sName "COOP (15-30) Tyrone Thrust"
 m_sAuthor "Til"
 m_sDescription "Russian Motor Rifles seize the village of Tyrone"
 m_sGameMode "#AR-ServerBrowser_ServerScenario"
 m_iPlayerCount 30
 m_GC_Metadata GC_MissionMetadata "{69DF2DD2D933E3CE}" {
  m_FriendlyForce GC_ForceDefinition "{69DF2DD33FC50F43}" {
   m_sFactionKey "RHS_AFRF"
   m_eType MECHANIZED
  }
  m_OpposingForce GC_ForceDefinition "{69DF2DD3342C7ECA}" {
   m_sFactionKey "FIA"
   m_eType LIGHT
  }
  m_eEra ERA_2020s
 }
}