SCR_MissionHeader {
 World "{A0BEE555BF959466}worlds/Blue/Ruckusberg/RuckusBerg.ent"
 m_sName "COTVT (56-69) Ruckus Berg"
 m_sAuthor "Blue"
 m_sDescription "USSR Mech COY plans to disrupt BLUFOR Convoy, while BLUFOR trys to delayed the ENY."
 m_iPlayerCount 69
}
