SCR_MissionHeader {
 World "{4105510FF77A3AD4}worlds/Blue/Bangalorious/LeadTheWay.ent"
 m_sName "TVT (75-98) Bangalorious"
 m_sAuthor "Blue"
 m_sDescription "American COY breaches a russian obstalce in order to sieze Torske Hill 35 Trenchline from USSR"
 m_iPlayerCount 98
 m_iMapMarkerLimitPerPlayer 99
}