SCR_MissionHeader {
 World "{4105510FF77A3AD4}worlds/Blue/Bangalorious/Bangalorious.ent"
 m_sName "TVT (75-98) Bangalorious"
 m_sAuthor "Blue"
 m_sDescription "American COY breaches a russian obstacle in order to sieze a trenchline on Torske Hill 35 from USSR."
 m_iPlayerCount 98
 m_iMapMarkerLimitPerPlayer 99
}