SCR_MissionHeader {
 World "{4105510FF77A3AD4}worlds/Blue/Bangalorious/Bangalorious.ent"
 m_sName "TVT (75-103) Bangalorious"
 m_sAuthor "Blue"
 m_sDescription "American COY breaches a russian obstacle in order to sieze a trenchline on Torske Hill 35 from USSR."
 m_iPlayerCount 103
 m_iMapMarkerLimitPerPlayer 99
 m_GC_Metadata GC_MissionMetadata "{69F0D8E440D18560}" {
  m_FriendlyForce GC_ForceDefinition "{69F0D8E4475E69BB}" {
   m_sFactionKey "US"
   m_eType LIGHT
  }
  m_OpposingForce GC_ForceDefinition "{69F0D8E446BAA2F9}" {
   m_sFactionKey "USSR"
   m_eType LIGHT
  }
  m_eEra ERA_1980s
  m_eSpecialAssets {
   ARTILLERY
  }
 }
}