SCR_MissionHeader {
 World "{C4B8B6187E756CD8}worlds/blackskimask/Deadly Crossing/DeadlyCrossing.ent"
 m_sName "TVT (55-79) Deadly Crossing"
 m_sAuthor "Blackskimask"
 m_sDescription " British light infantry platoon defends river crossing from separatists with drones and BMP support. TVT MIN 55 MAX 79. 1.7:1 ratio"
 m_iPlayerCount 79
}