SCR_MissionHeader {
 World "{8A802BC0E6403A23}worlds/blackskimask/Plant Attack/PlantAttack.ent"
 m_sName "TVT (60-93) Plant Attack "
 m_sAuthor "Blackskimask"
 m_sDescription "British rifle company attacks power plant held by Separatists. TVT MIN 60 MAX 93"
 m_iPlayerCount 93
}