SCR_MissionHeader {
 World "{77BF2245E07ED898}worlds/blackskimask/ZarichneFront/ZarichneFront.ent"
 m_sName "COTVT (40-65) Zarichne Front "
 m_sAuthor "blackskimask"
 m_sDescription "ACOY 1RIFLES conduct probing attack on Russian trench."
 m_iPlayerCount 65
}