SCR_MissionHeader {
 World "{3BD0B77A257CF381}worlds/TheLocalPub/BarnyardBashers/BarnyardBashers.ent"
 m_sName "COTVT (20-36) Barnyard Bashers"
 m_sAuthor "TheLocalPub"
 m_sDescription "British forces must sweep and secure a series of farmyards along an MSR that have been used by the Irish Republican Army to conduct sporadic attacks against passing convoys and occasional civilian traffic."
 m_sDetails "British forces must sweep and secure a series of farmyards along an MSR that have been used by the Irish Republican Army to conduct sporadic attacks against passing convoys and occasional civilian traffic."
 m_iPlayerCount 36
 m_iStartingHours 5
 m_iStartingMinutes 56
 m_GC_Metadata GC_MissionMetadata "{6A1708DC94302A3A}" {
  m_FriendlyForce GC_ForceDefinition "{6A1708DC9519EA82}" {
   m_sFactionKey "UK"
   m_eType MOTORIZED
  }
  m_OpposingForce GC_ForceDefinition "{6A1708DC8EA5FFBB}" {
   m_sFactionKey "IRA"
   m_eType LIGHT
  }
  m_eEra ERA_1990s
 }
}