SCR_MissionHeader {
 World "{92EE2F6986884405}worlds/TheLocalPub/BlockDefenders/BlockDefenders.ent"
 m_sName "COTVT (30-67) Block Defenders"
 m_sAuthor "TheLocalPub"
 m_sDescription "British forces must fight their way through a dense urban city in order to reach and occupy a key highway before Iraqi reinforcements arrive."\
 "Time is limited, resistance is expected to be heavy, and failure to secure the route in time could allow enemy forces to reinforce the battle further north."\
 "Will the Brits make it in time?"
 m_sDetails "British forces must fight their way through a dense urban city in order to reach and occupy a key highway before Iraqi reinforcements arrive."\
 "Time is limited, resistance is expected to be heavy, and failure to secure the route in time could allow enemy forces to reinforce the battle further north."\
 "Will the Brits make it in time?"
 m_iPlayerCount 67
}