SCR_MissionHeader {
 World "{15FFB74F07D5194E}worlds/TheLocalPub/LongmoorLashings/LongmoorLashings.ent"
 m_sName "COOP (15-28) Bug Out"
 m_sAuthor "TheLocalPub"
 m_sDescription "British forces on must break out from their compromised platoon harbour after coming under attack. Repel the initial assault before fighting your way to the extraction area while pursued by Argentinian troops."\
 ""\
 "Will the platoon break contact and escape, or be overrun before reaching extraction?"
 m_sDetails "British forces on must break out from their compromised platoon harbour after coming under attack. Repel the initial assault before fighting your way to the extraction area while pursued by Argentinian troops."\
 ""\
 "Will the platoon break contact and escape, or be overrun before reaching extraction?"
 m_iPlayerCount 28
 m_iStartingHours 12
 m_GC_Metadata GC_MissionMetadata "{6A1084937BABFE70}" {
  m_FriendlyForce GC_ForceDefinition "{6A10849378F5682A}" {
   m_sFactionKey "UK"
   m_eType LIGHT
  }
  m_OpposingForce GC_ForceDefinition "{6A1084937DC0ED43}" {
   m_sFactionKey "GC_ARG"
   m_eType LIGHT
  }
  m_eEra ERA_1980s
 }
}