SCR_MissionHeader {
 World "{6E9E31D1F16C3D3F}worlds/TheLocalPub/CimicHouse/CimicHouse.ent"
 m_sName "COTVT (10-36) Cimic House"
 m_sAuthor "TheLocalPub"
 m_sDescription "A British platoon must defend CIMIC House against a large-scale Iraqi assault aimed at overrunning and capturing the compound."\
 "Can the garrison hold long enough to force the attackers to withdraw?"
 m_sDetails "A British platoon must defend CIMIC House against a large-scale Iraqi assault aimed at overrunning and capturing the compound."\
 "Can the garrison hold long enough to force the attackers to withdraw?"
 m_iPlayerCount 36
 m_iStartingHours 12
}