SCR_MissionHeader {
 World "{B8F7CC979E05A7CE}worlds/TheLocalPub/IraqiCheckpoint/IraqiCheckpoint.ent"
 m_sName "TVT (25-77) Iraqi Checkpoint"
 m_sAuthor "TheLocalPub"
 m_sDescription "A major insurgent force is preparing to assault an Iraqi Army checkpoint north of Al-Hadra. The position controls a key stretch of highway that insurgent forces need secured in order to move men and equipment through the region freely."\
 "Outnumbered Iraqi defenders are expected to face a heavy attack as both sides fight for control of the route."
 m_sDetails "A major insurgent force is preparing to assault an Iraqi Army checkpoint north of Al-Hadra. The position controls a key stretch of highway that insurgent forces need secured in order to move men and equipment through the region freely."\
 "Outnumbered Iraqi defenders are expected to face a heavy attack as both sides fight for control of the route."
 m_iPlayerCount 77
}