SCR_MissionHeader {
 World "{4686580AAF58BDDF}worlds/TheLocalPub/Joutus/Joutus.ent"
 m_sName "COTVT (20-33) Joutus"
 m_sAuthor "TheLocalPub"
 m_sDescription "Canadian forces have been pursuing an FIA cell for several days. Isolated, cut off, and fixed in location, the FIA cell makes it's final stand. Can they repel the Canadian assault?"
 m_sDetails "Canadian forces have been pursuing an FIA cell for several days. Isolated, cut off, and fixed in location, the FIA cell makes it's final stand. Can they repel the Canadian assault?"
 m_iPlayerCount 33
 m_GC_Metadata GC_MissionMetadata "{6A3CCAAA83FC4FF6}" {
  m_FriendlyForce GC_ForceDefinition "{6A3CCAAA8081D872}" {
   m_sFactionKey "GC_CAF"
   m_eType MOTORIZED
  }
  m_OpposingForce GC_ForceDefinition "{6A3CCAAA84E515B6}" {
   m_sFactionKey "FIA"
   m_eType LIGHT
  }
  m_eEra ERA_2020s
  m_eSpecialAssets {
   DRONES
  }
 }
}