SCR_MissionHeader {
 World "{8D5AF1ABEEB558B0}worlds/TheLocalPub/QuickReaction/QuickReactions.ent"
 m_sName "COTVT (50-99) Quick Reactions"
 m_sAuthor "TheLocalPub"
 m_sDescription "Insurgents have launched a surprise raid on the presidential palace in the early morning hours. Can Iraqi security forces hold off long enough for US forces to reach the compound and extract the HVTs before it's completely overrun?"
 m_sDetails "Insurgents have launched a surprise raid on the presidential palace in the early morning hours. Can Iraqi security forces hold off long enough for US forces to reach the compound and extract the HVTs before it's completely overrun?"
 m_iPlayerCount 99
}