SCR_MissionHeader {
 World "{1395C050CE417167}worlds/TheLocalPub/RapidAttack/RapidAttack.ent"
 m_sName "COOP (20-26) Rapid Attack"
 m_sAuthor "TheLocalPub"
 m_sDescription "A hasty Canadian assault to dislodge FIA forces from a barnyard and secure the surrounding area."
 m_sDetails "A hasty Canadian assault to dislodge FIA forces from a barnyard and secure the surrounding area."
 m_iPlayerCount 26
 m_iStartingHours 13
 m_iStartingMinutes 35
 m_GC_Metadata GC_MissionMetadata "{6A3ED8C3E8AFDD4D}" {
  m_FriendlyForce GC_ForceDefinition "{6A3ED8C3E8AFD2E9}" {
   m_sFactionKey "GC_CAF"
   m_eType LIGHT
  }
  m_OpposingForce GC_ForceDefinition "{6A3ED8C3E8AFD2EA}" {
   m_sFactionKey "FIA"
   m_eType LIGHT
  }
  m_eEra ERA_2020s
 }
}