SCR_MissionHeader {
 World "{20CACBE0D7D21595}worlds/TheLocalPub/TakingTrenches/TakingTrenches.ent"
 m_sName "COTVT (15-28) Taking Trenches"
 m_sAuthor "TheLocalPub"
 m_sDescription "Special forces from the Chernarus Defence Force conduct a deliberate assault to secure a Russian headquarters operating along the Zherebets river."
 m_sDetails "Special forces from the Chernarus Defence Force conduct a deliberate assault to secure a Russian headquarters operating along the Zherebets river."
 m_iPlayerCount 28
 m_GC_Metadata GC_MissionMetadata "{6A367EBCF57BF0B0}" {
  m_FriendlyForce GC_ForceDefinition "{6A367EBCEA57DAE1}" {
   m_sFactionKey "GC_CDF"
   m_eType LIGHT
  }
  m_OpposingForce GC_ForceDefinition "{6A367EBCE399A609}" {
   m_sFactionKey "RHS_AFRF"
   m_eType LIGHT
  }
  m_eEra ERA_2020s
  m_eSpecialAssets {
   DRONES
  }
 }
}