SCR_MissionHeader {
 World "{1AEB491E5E4F6D05}worlds/TheLocalPub/WetFeet/WetFeet.ent"
 m_sName "TVT (25-54) Wet Feet"
 m_sAuthor "TheLocalPub"
 m_sDescription "British light infantry move to assault a separatist-held hamlet in the Ruha region, where entrenched fighters have fortified a checkpoint along a key Alternative Supply Route. The outcome of the engagement will determine whether the route is reopened to government forces or remains under separatist control."\
 ""
 m_sDetails "British light infantry move to assault a separatist-held hamlet in the Ruha region, where entrenched fighters have fortified a checkpoint along a key Alternative Supply Route. The outcome of the engagement will determine whether the route is reopened to government forces or remains under separatist control."\
 ""
 m_iPlayerCount 54
}