SCR_MissionHeader {
 World "{B4EF3C3BF65879AE}worlds/HitTheMan/Frontline CDF Construction Site/FrontlineCDFConstructionSite.ent"
 m_sName "TVT (60-76) Frontline CDF - Construction Site V1"
 m_sAuthor "HitTheMan"
 m_sDescription "Seperatists and the Chernarussian Defence Force have been battling over this construction site for months, with the CDF continuing to try and retake it while the Seperatists are steadfast. This is just another attempt by the CDF."
 m_sGameMode "#AR-ServerBrowser_ServerScenario"
 m_iPlayerCount 79
}