SCR_MissionHeader {
 World "{1EA95DAE3230BEB0}worlds/Cain/Cain.ent"
 m_sName "TVT (70-99) Brits at Beauregard"
 m_sAuthor "RedTheKnown"
 m_sDescription "British motorized force conducts an early morning assault against a recently landed Russian naval infantry force awaiting reinforcement. Year:1995"
 m_sGameMode "TVT"
 m_iPlayerCount 99
 m_iStartingHours 4
}