SCR_MissionHeader {
 World "{B4EE39AD58F39002}worlds/RedTheKnown/ChakChakChosen/ChakChakChosen.ent"
 m_sName "TVT (65-110) Chak Chak Chosen"
 m_sAuthor "RedTheKnown"
 m_sDescription "Isolated Takistan Army infantry force defends against Rebel assault. 65-110 Player TVT"
 m_sGameMode "TVT"
 m_iPlayerCount 110
 m_iStartingHours 19
}