SCR_MissionHeader {
 World "{B4EE39AD58F39002}worlds/RedTheKnown/ChakChakChosen/ChakChakChosen.ent"
 m_sName "TVT (50-113) Chak Chak Chosen"
 m_sAuthor "RedTheKnown"
 m_sDescription "Isolated Takistan Army infantry force defends against Rebel assault. 50-121 Player TVT"
 m_sGameMode "TVT"
 m_iPlayerCount 121
 m_iStartingHours 19
}