SCR_MissionHeaderScenarioFramework {
 World "{9DE1D4EFC33B492F}worlds/Jub/ALHADRA RUMBLE/ALHADRA RUMBLE.ent"
 m_sName "TVT (50-128) Al Hadra Rumble"
 m_sAuthor "jubxxxjub"
 m_sDescription "The year is 2025. In a remote desert sector, USMC forces have moved to secure a pair of critical transit bridges spanning a river. The sector is heavily occupied by the \"Varan Group,\" a heavily armed Russian Private Military Company operating under a shadow contract. Varan Group has deployed a full company-sized element, supported by localized Electronic Warfare (EW) and a dense swarm of FPV drones, to seize the crossings and crush the Marine presence."
 m_sGameMode "TVT"
 m_iPlayerCount 128
}