SCR_MissionHeaderScenarioFramework {
 World "{67BB62D6850D45FB}worlds/Jub/CobrasBite/Cobras_bite.ent"
 m_sName "CO (30-63) Cobras Bite"
 m_sAuthor "jubxxxjub"
 m_sDescription "A USMC Rifle platoon + CAAT team and ACE conduct a hasty defense to delay attacking Russian motor rifles before regrouping with friendlies."
 m_sGameMode "Coop"
 m_iPlayerCount 63
}