SCR_MissionHeaderScenarioFramework {
 World "{65D6D3642BA2D5DC}worlds/Jub/CombinedAntiArmorTeam/CombinedAntiArmorTeam.ent"
 m_sName "COOP (20-40) Combined Anti Armor Team"
 m_sAuthor "jubxxxjub"
 m_sDescription "A USMC Rifle platoon(-), CAAT Section and ACE conduct a hasty defense to support a UK recon platoon to the NorthWest."
 m_sGameMode "COOP"
 m_iPlayerCount 40
}