SCR_MissionHeader {
 World "{0A04EF216B35C42B}worlds/Jub/LightArmoredRecon/LightArmoredRecon.ent"
 m_sName "COOP (16-28) Duck Hunt"
 m_sAuthor "jubxxxjub"
 m_sDescription "USMC LAR support an attack on RU forces"
 m_sGameMode "COOP"
 m_iPlayerCount 28
}