SCR_MissionHeader {
 World "{527BD1432950EC41}worlds/Jub/OperationArrowhead2TwoBloodyMiles/OperationArrowhead2TwoBloodyMiles.ent"
 m_sName "COOP (15-26) Operation Arrowhead Two Bloody Miles"
 m_sAuthor "jubxxxjub"
 m_sDescription "An M1A1 armor section, CAAT section, and FO team with an M777 element conduct a violent route clearance two miles north along the ASR, secured by rolling waves of infantry."
 m_sGameMode "COOP"
 m_iPlayerCount 26
 m_GC_Metadata GC_MissionMetadata "{6A6E1A6020486931}" {
  m_FriendlyForce GC_ForceDefinition "{6A6E1A602175886F}" {
   m_sFactionKey "RHS_USAF"
   m_eType COMBINED
  }
  m_OpposingForce GC_ForceDefinition "{6A6E1A6038230558}" {
   m_sFactionKey "GC_TKA"
   m_eType COMBINED
  }
  m_eEra ERA_2000s
 }
}