SCR_MissionHeader {
 World "{527BD1432950EC41}worlds/Jub/OperationArrowhead2TwoBloodyMiles/OperationArrowhead2TwoBloodyMiles.ent"
 m_sName "COOP (15-26) Operation Arrowhead 2 Two Bloody Miles"
 m_sAuthor "jubxxxjub"
 m_sDescription "An M1A1 armor section, CAAT section, and FO team with an M777 element conduct a violent route clearance two miles north along the ASR, secured by rolling waves of infantry."
 m_sGameMode "COOP"
 m_iPlayerCount 26
}