SCR_MissionHeader {
 World "{4CC0153F97F64DDC}worlds/Jub/OperationArrowheadIronCipher/OperationArrowheadIronCipher.ent"
 m_sName "COOP (16-28) Operation Arrowhead Iron Cipher"
 m_sAuthor "jubxxxjub"
 m_sDescription "US SF and RANGERs fly to seize TKA intel"
 m_sGameMode "COOP"
 m_iPlayerCount 28
 m_GC_Metadata GC_MissionMetadata "{6A82132B15949E25}" {
  m_FriendlyForce GC_ForceDefinition "{6A82132B12C2156B}" {
   m_sFactionKey "RHS_USAF"
   m_eType AIRMOBILE
  }
  m_OpposingForce GC_ForceDefinition "{6A82132B2FB7602C}" {
   m_sFactionKey "GC_TKA"
   m_eType COMBINED
  }
  m_eEra ERA_2000s
  m_eSpecialAssets {
   ATK_HELIS
  }
 }
}