SCR_MissionHeaderScenarioFramework {
 World "{CFD361681DEC28AD}worlds/Jub/OperationJaws/OperationJaws.ent"
 m_sName "TVT (50-94) Operation Jaws"
 m_sAuthor "jubxxxjub"
 m_sDescription "The year is 2012, USMC forces in Hemland provence have started Op Jaws to destroy and demoralize Taliban forces prior to passing off combat ops to the ANA"
 m_sGameMode "TVT"
 m_iPlayerCount 94
}