SCR_MissionHeader {
 World "{4F03E074D58CA059}worlds/HitTheMan/Mountainous Mujahideen/MountainousMujahideen.ent"
 m_sName "TVT (55-74) Mountainous Mujahideen"
 m_sAuthor "HitTheMan"
 m_sDescription "Soviets forces has been clashing with the local Mujahideen for the past few months, Soviet Command has issued the order to seize the village on the mountains from the control of the Mujahideen, and try to establish dominance in the mountains themselves."
 m_sGameMode "#AR-ServerBrowser_ServerScenario"
 m_iPlayerCount 79
}