SCR_MissionHeader {
 World "{B587B01692B5BAD5}worlds/arc/BrambledeepBypass/BrambledeepBypass.ent"
 m_sName "TVT (65-81) Brambledeep Bypass"
 m_sAuthor "arc"
 m_sDescription "USMC Rifle Platoon+ attempts to clear Russian motor rifle recon from a nearby MSR, 2009."
 m_iPlayerCount 81
}