SCR_MissionHeader {
 World "{EFBC64965A33129F}worlds/arc/FactorySiegeRedux/FactorySiegeRedux.ent"
 m_sName "COTVT (55-72) Factory Siege Redux"
 m_sAuthor "arc"
 m_sDescription "US Stryker Platoon attempts to seize a MSV-held factory, 2004"
 m_iPlayerCount 72
}