SCR_MissionHeader {
 World "{39AFBF5961C99E60}worlds/arc/LeMouleApproachRedux/LeMouleApproachRedux.ent"
 m_sName "COTVT (45-62) Le Moule Approach Redux"
 m_sAuthor "arc"
 m_sDescription "2004, US Army rifle platoon attempts to secure a VDV-occupied sawmill."
 m_iPlayerCount 62
}