SCR_MissionHeader {
 World "{E9B3EBB5287D42E7}worlds/arc/ProvinsApproachRedux/ProvinsApproachRedux.ent"
 m_sName "COTVT (50-68) Provins Approach Redux"
 m_sAuthor "arc"
 m_sDescription "USMC Rifle Platoon attempt to seize a checkpoint from RU Motor Rifles, 2008"
 m_iPlayerCount 68
}