SCR_MissionHeader {
 World "{DF43635EC51DEC8A}worlds/arc/VilleneufPunchupRedux/VilleneufPunchupRedux.ent"
 m_sName "TVT (55-76) Villeneuf Punchup Redux"
 m_sAuthor "arc"
 m_sDescription "VDV Coy- assault a CAF-held village on Everon's coast. Original by Woody."
 m_iPlayerCount 76
}