SCR_MissionHeader {
 World "{CD4236F4C3A4848C}worlds/Perfk/AbadDayinKunarUS/AbadDayinKunarUS.ent"
 m_sName "COTVT (60-104) Abad Day in Kunar US"
 m_sAuthor "Perfk"
 m_sDescription "US marines clear Kunar Abad of entrenched Mujahideen fighters"
 m_iPlayerCount 104
}