SCR_MissionHeader {
 World "{E299D715AAD3EB0B}worlds/Corax/Hnevice/Hnevice.ent"
 m_sName "TVT (50-68) Hnevice"
 m_sAuthor "Plagemonk"
 m_sDescription "San serrife attacks a town"
 m_sGameMode "#AR-ServerBrowser_ServerScenario"
 m_iPlayerCount 68
}