SCR_MissionHeader {
 World "{4F74B118840009EC}worlds/TemplateMission/TemplateMission.ent"
 m_sName "COOP (15-30) MyMissionNameHere"
 m_sAuthor "TheLocalPub"
 m_sDescription "Copy the mission summary you used in your briefing tab or write something similar."
 m_sDetails "Copy the mission summary you used in your briefing tab or write something similar."
 m_iPlayerCount 30
 m_GC_Metadata GC_MissionMetadata "{6A729201E76ECB17}" {
  m_FriendlyForce GC_ForceDefinition "{6A729201E4595362}" {
   m_sFactionKey "US"
   m_eType LIGHT
  }
  m_OpposingForce GC_ForceDefinition "{6A729201D8044FF4}" {
   m_sFactionKey "USSR"
   m_eType ARMORED
  }
  m_eEra ERA_1990s
 }
}