SCR_MissionHeader {
 World "{C0272EBB573FC9D1}worlds/Barwick/The Blood and Smoke/The Blood and Smoke.ent"
 m_sName "COTVT (30-46) The Blood and Smoke"
 m_sAuthor "Barwick"
 m_sDescription "SEALS trapped in a city attempt to exfil with BFVs under heavy insurgent fire."
 m_iPlayerCount 46
}