SCR_MissionHeader {
 World "{714ABB04B13C9853}worlds/chllboy/Gigantomachia/Gigantomachia.ent"
 m_sName "TVT (42-54) Gigantomachia"
 m_sAuthor "chillboy"
 m_sDescription "U.S. understrength infantry platoon defends an OP from insurgents w/ drones"
 m_iPlayerCount 54
}