SCR_MissionHeader {
 World "{01C3D8F58C47871D}worlds/chllboy/Hephaestus's forge/Haphaestus's forge.ent"
 m_sName "TVT (64-80) Haphaestus's forge"
 m_sAuthor "chillboy"
 m_sDescription "A platoon from the 75th Ranger Regiment conducts a night air assault to destroy an IED drone manufacturing facility, gather intelligence and seize weaponry. Insurgents defend with drones."
 m_iPlayerCount 80
}