SCR_MissionHeader {
 World "{22E75D3543B7D656}worlds/chllboy/Hephaestus Forge/Hephaestus Forge.ent"
 m_sName "TVT (64-80) Hephaestus Forge"
 m_sAuthor "chillboy"
 m_sDescription "A platoon from the 75th Ranger Regiment conducts a night air assault to destroy an IED drone manufacturing facility, gather intelligence and seize weaponry. Insurgents defend with drones."
 m_iPlayerCount 80
}