SCR_MissionHeader {
 World "{74E330896733EF8A}worlds/chllboy/Makeup/Makeup.ent"
 m_sName "TVT (60-82) Makeup"
 m_sAuthor "chillboy"
 m_sDescription "AFRF/SSO tactical detachment search for FIA ammunition caches in Javory."
 m_iPlayerCount 82
}