SCR_MissionHeader {
 World "{C96ECC406F91E668}worlds/chllboy/Trifecta/Trifecta.ent"
 m_sName "TVT (70-85) Trifecta"
 m_sAuthor "chillboy"
 m_sDescription "Rivaling PMCs and a local FIA cell compete to extract a Satellite Targeting Module."
 m_iPlayerCount 85
}