SCR_MissionHeader {
 World "{B9234B4077C6522F}worlds/Wade/NightSeizure/NightSeizure.ent"
 m_sName "TVT (24-52) Night Seizure"
 m_sAuthor "Wade"
 m_sDescription "U.S. SF conducts raid to secure intel"
 m_iPlayerCount 52
 m_GC_Metadata GC_MissionMetadata "{69DF3AE64EC160EB}" {
  m_FriendlyForce GC_ForceDefinition "{69DF3AE64DBD3A37}" {
   m_sFactionKey "US"
   m_eType LIGHT
  }
  m_OpposingForce GC_ForceDefinition "{69DF3AE64DF5D025}" {
   m_sFactionKey "USSR"
   m_eType LIGHT
  }
  m_eEra ERA_1980s
  m_eSpecialAssets {
   MORTARS
  }
 }
}