SCR_MissionHeader {
 World "{B9234B4077C6522F}worlds/Wade/NightSeizure/NightSeizure.ent"
 m_sName "TVT 24-48 Night Seizure"
 m_sAuthor "Wade"
 m_sDescription "U.S. SF conducts raid to secure intel"
 m_iPlayerCount 48
}