SCR_MissionHeader {
 World "{28EFCC5DBB854FCE}worlds/Wade/TheLocalFiles/TheLocalFiles.ent"
 m_sName "TVT (50-67) TheLocalFiles"
 m_sAuthor "Wade"
 m_sDescription "Two teams attempt to capture an HVT"
 m_iPlayerCount 67
 m_GC_Metadata GC_MissionMetadata "{69DF49DEB4050AC0}" {
  m_FriendlyForce GC_ForceDefinition "{69DF49DEB50A9900}" {
   m_sFactionKey "RHS_USAF"
   m_eType AIRMOBILE
  }
  m_OpposingForce GC_ForceDefinition "{69DF49DEB55BA373}" {
   m_sFactionKey "RHS_AFRF"
   m_eType AIRMOBILE
  }
  m_eEra ERA_2020s
 }
}