SCR_MissionHeader {
 World "{EF5A2D0CAED36D77}worlds/Sasha20k_pro/Assault of Thirty Palms/Assault of Thirty Palms.ent"
 m_sName "COOP (20-48) Assault of Thirty Palms"
 m_sAuthor "sasha20k_pro"
 m_sDescription "US Marines Assault the FOB of Thirty Palms"
 m_iPlayerCount 48
 m_GC_Metadata GC_MissionMetadata "{6A4B0E0C558985DA}" {
  m_FriendlyForce GC_ForceDefinition "{6A4B0E0C56256F88}" {
   m_sFactionKey "RHS_USAF"
   m_eType MOTORIZED
  }
  m_OpposingForce GC_ForceDefinition "{6A4B0E0C689E342B}" {
   m_sFactionKey "GC_INSURGENT"
   m_eType LIGHT
  }
  m_eEra ERA_2020s
 }
}