SCR_MissionHeader {
 World "{0ED36C6EE5435D9B}worlds/Woody/COTVTXX_Karachinar_Crashout/COTVTXX_Karachinar_Crashout.ent"
 m_sName "COTVT (50-83) Karachinar Crashout"
 m_sAuthor "Woody"
 m_sDescription "Soviet Motor Rifles and Mujahideen fight over some different dirt houses."
 m_iPlayerCount 83
 m_iMapMarkerLimitPerPlayer 99
 m_GC_Metadata GC_MissionMetadata "{69DF3AE5E3653880}" {
  m_FriendlyForce GC_ForceDefinition "{69DF3AE5E011B4F3}" {
   m_sFactionKey "USSR"
   m_eType MECHANIZED
  }
  m_OpposingForce GC_ForceDefinition "{69DF3AE5E05F534F}" {
   m_sFactionKey "GC_MUJ"
   m_eType LIGHT
  }
  m_eEra ERA_1980s
 }
}