SCR_MissionHeaderScenarioFramework {
 World "{95DC129C49DA2DC7}worlds/Woody/COTVTXX_Kassel_Crashers_MODERN_REDUX/COTVTXX_Kassel_Crashers_MODERN_REDUX.ent"
 m_sName "COTVT (50-69) Kassel Crashers MODERN REDUX"
 m_sAuthor "Woody And Jub"
 m_sDescription "Modernized Soviet Motor Rifle Company (44th MRC) spearheads a high-intensity flanking assault on US Army Stryker Dragoons defending the village of Kassel near Bad Orb."
 m_iPlayerCount 69
 m_GC_Metadata GC_MissionMetadata "{69DF3AE46647CD1B}" {
  m_FriendlyForce GC_ForceDefinition "{69DF3AE4674A0C3A}" {
   m_sFactionKey "RHS_AFRF"
   m_eType MECHANIZED
  }
  m_OpposingForce GC_ForceDefinition "{69DF3AE464253945}" {
   m_sFactionKey "RHS_USAF"
   m_eType MECHANIZED
  }
  m_eEra ERA_2020s
  m_eSpecialAssets {
   MORTARS
  }
  m_MissionGroup GC_MissionGroupDefinition "{69DF3AE45B62AC6F}" {
   m_sGroupID "KasselCrashers"
   m_fGroupSimilarity 0.75
  }
 }
}