SCR_MissionHeader {
 World "{184DD2B863AEA495}worlds/Woody/COTVTXX_Zavarak_Farmland/COTVTXX_Zavarak_Farmland.ent"
 m_sName "COTVT (50-75) Zavarak Farmland"
 m_sAuthor "Woody"
 m_sDescription "Soviet Motor Rifles and Mujahideen fight over some dirt houses."
 m_iPlayerCount 75
 m_GC_Metadata GC_MissionMetadata "{69DF3AE441446C8D}" {
  m_FriendlyForce GC_ForceDefinition "{69DF3AE441B13EA4}" {
   m_sFactionKey "USSR"
   m_eType MECHANIZED
  }
  m_OpposingForce GC_ForceDefinition "{69DF3AE4441FD7E3}" {
   m_sFactionKey "GC_MUJ"
   m_eType LIGHT
  }
  m_eEra ERA_1980s
 }
}