SCR_MissionHeader {
 World "{361B45D7A3EE3F73}worlds/Woody/COTVTXX_Kassel_Crashers/COTVTXX_Kassel_Crashers.ent"
 m_sName "COTVT (50-69) Kassel Crashers"
 m_sAuthor "Woody"
 m_sDescription "Soviet Motor Rifle Company assaults a village near Bad Orb."
 m_iPlayerCount 69
 m_iMapMarkerLimitPerPlayer 99
 m_GC_Metadata GC_MissionMetadata "{69DF3AE5DFB516E9}" {
  m_FriendlyForce GC_ForceDefinition "{69DF3AE5DCE84207}" {
   m_sFactionKey "USSR"
   m_eType MECHANIZED
  }
  m_OpposingForce GC_ForceDefinition "{69DF3AE5DD079E91}" {
   m_sFactionKey "US"
   m_eType MECHANIZED
  }
  m_eEra ERA_1980s
  m_eSpecialAssets {
   MORTARS
  }
  m_MissionGroup GC_MissionGroupDefinition "{69DF3AE4A33EAC20}" {
   m_sGroupID "KasselCrashers"
   m_fGroupSimilarity 0.75
  }
 }
}