SCR_MissionHeader {
 World "{BB411D18132130CB}worlds/Woody/COXX_Hof_Lomelsberg_Flank/COXX_Hof_Lomelsberg_Flank.ent"
 m_sName "COOP (30-44) Hof Lomelsberg Flank"
 m_sAuthor "Woody"
 m_sDescription "Soviet motorised reconnassaince company flanks a US V Corps mechanised infantry company."
 m_iPlayerCount 44
 m_iMapMarkerLimitPerPlayer 99
 m_GC_Metadata GC_MissionMetadata "{69DF3AE7399F7337}" {
  m_FriendlyForce GC_ForceDefinition "{69DF3AE703F665D3}" {
   m_sFactionKey "USSR"
   m_eType MECHANIZED
  }
  m_OpposingForce GC_ForceDefinition "{69DF3AE703126DA8}" {
   m_sFactionKey "US"
   m_eType MECHANIZED
  }
  m_eEra ERA_1980s
 }
}