SCR_MissionHeader {
 World "{E5440CC8835F9FC8}worlds/Woody/COXX_Torske_Crossing/COXX_Torske_Crossing.ent"
 m_sName "COOP (40-64) Torske Crossing"
 m_sAuthor "Woody"
 m_sDescription "Estonia, 2024 | 1 RIFLES Coy(-) conducts an attack and contested river crossing."
 m_iPlayerCount 64
 m_iMapMarkerLimitPerPlayer 99
 m_GC_Metadata GC_MissionMetadata "{69DF3AE749AA9E52}" {
  m_FriendlyForce GC_ForceDefinition "{69DF3AE74F457695}" {
   m_sFactionKey "UK"
   m_eType LIGHT
  }
  m_OpposingForce GC_ForceDefinition "{69DF3AE74ECFADBB}" {
   m_sFactionKey "RHS_AFRF"
   m_eType LIGHT
  }
  m_eEra ERA_2020s
 }
}