SCR_MissionHeader {
 World "{C1A3EEB8040DFB87}worlds/Woody/COXX_Landay_Haul/COXX_Landay_Haul.ent"
 m_sName "COOP (40-60) Landay Haul"
 m_sAuthor "Woody"
 m_sDescription "Takistan Army (TKA) mechanized infantry sweep of two rebel held villages."
 m_iPlayerCount 60
 m_iMapMarkerLimitPerPlayer 99
 m_GC_Metadata GC_MissionMetadata "{69DF3AE71706B566}" {
  m_FriendlyForce GC_ForceDefinition "{69DF3AE7142E9903}" {
   m_sFactionKey "GC_TKA"
   m_eType MECHANIZED
  }
  m_OpposingForce GC_ForceDefinition "{69DF3AE71447701E}" {
   m_sFactionKey "GC_INSURGENT"
   m_eType LIGHT
  }
  m_eEra ERA_2000s
 }
}