SCR_MissionHeader {
 World "{582D5DFAA827CC52}worlds/Woody/COXX_Funf_Wege_Lodgement/COXX_Funf_Wege_Lodgement.ent"
 m_sName "COOP (40-58) Funf Wege Lodgement"
 m_sAuthor "Woody"
 m_sDescription "DDR motor rifle company flanks a UK I Corps light infantry company."
 m_iPlayerCount 58
 m_iMapMarkerLimitPerPlayer 99
 m_GC_Metadata GC_MissionMetadata "{69DF3AE4B8F0364F}" {
  m_FriendlyForce GC_ForceDefinition "{69DF3AE4B9B3B1BA}" {
   m_sFactionKey "GC_NVA"
   m_eType MECHANIZED
  }
  m_OpposingForce GC_ForceDefinition "{69DF3AE4B901DCBE}" {
   m_sFactionKey "UK"
   m_eType LIGHT
  }
  m_eEra ERA_1980s
 }
}