SCR_MissionHeader {
 World "{E960440C33E347BD}worlds/Woody/TVTXX_Waterside_Punchup/TVTXX_Waterside_Punchup.ent"
 m_sName "TVT (40-51) Waterside Punchup"
 m_sAuthor "Woody"
 m_sDescription "Royal Marines Commandos battle FIA Separatists on the St. Phillipe coast."
 m_iPlayerCount 51
 m_GC_Metadata GC_MissionMetadata "{69DF3AE7A69EDCAE}" {
  m_FriendlyForce GC_ForceDefinition "{69DF3AE7A4877242}" {
   m_sFactionKey "UK"
   m_eType LIGHT
  }
  m_OpposingForce GC_ForceDefinition "{69DF3AE7A87B9D06}" {
   m_sFactionKey "GC_SEPARATIST"
   m_eType LIGHT
  }
  m_eEra ERA_2020s
 }
}