SCR_MissionHeader {
 World "{EF5A2D0CAED36D77}worlds/Sasha20k_pro/Assault of Thirty Palms/Assault of Thirty Palms.ent"
 m_sName "COOP (20-48)"
 m_sAuthor "sasha20k_pro"
 m_sDescription "US Marines Assault the FOB of Thirty Palms"
 m_iPlayerCount 48
}