name: Sync Fork Master

on:
  schedule:
    - cron: "*/10 * * * *"   # Runs daily at 03:00 UTC
  workflow_dispatch:       # Manual trigger

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout the master branch (the one we want to sync)
      - name: Checkout fork master
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: master      # This checks out master, not the workflow branch
          fetch-depth: 0

      # 2️⃣ Add upstream repository
      - name: Add upstream remote
        run: git remote add upstream https://github.com/Global-Conflicts-ArmA/gc-reforger-missions.git

      # 3️⃣ Fetch upstream changes
      - name: Fetch upstream
        run: git fetch upstream

      # 4️⃣ Hard reset master to upstream (safe since no local changes)
      - name: Reset master to match upstream
        run: |
          git checkout master
          git reset --hard upstream/master
          git push origin master --force
