SCR_MissionHeader {
 World "{99E9B3A3BC344847}worlds/CO63_StashedCache_v2/CO63_StashedCache_v2.ent"
 m_sName "COOP (34-63) Stashed Cache"
 m_sAuthor "HelloCam3"
 m_sDescription "A Soviet motorised naval infantry company moves to capture a large FIA supply cache."
 m_iPlayerCount 63
 m_bMapMarkerEnableDeleteByAnyone 1
 m_iMapMarkerLimitPerPlayer 99
}